== Camel with Spring Boot 2 JTA XA 2PC

This example demonstrates how to run a Camel Service on Spring-Boot 2 that supports XA transactions on two external transactional resources: a JMS resource (A-MQ) and a database (PostgreSQL).
It also shows how to use transaction propagations.

== Run on local workstation

 mvn -D"spring-boot.run.profiles"=local

=== Database PostgreSQL

Reference: https://hub.docker.com/_/postgres/

[source,bash]
----
$ docker volume create pgdata

$ docker run --name postgres -e POSTGRES_PASSWORD=secret -d -p 54320:5432 -v pgdata:/var/lib/postgresql/data postgres:9.6 -c 'max_connections=200' -c 'max_prepared_transactions=100'

$ docker exec -i postgres psql -U postgres -c "CREATE DATABASE sampledb WITH ENCODING='UTF8' OWNER=postgres;"
----

=== Database Derby

Sadly I could not get it working with the Apache Derby database network connection.

=== AMQ Broker

Instructions still to write.

== Deploy on OpenShift

Reference: https://access.redhat.com/documentation/en-us/red_hat_fuse/7.5/html/fuse_on_openshift_guide/camel-spring-boot-application-with-xa-transactions

Install the Fuse imagestreams and templates on the OpenShift 4.x server

https://access.redhat.com/documentation/en-us/red_hat_fuse/7.5/html/fuse_on_openshift_guide/get-started-admin#install-fuse-on-openshift4

=== Prepare

Watch the username and password.
Has to be the same as in application.properties


oc new-app --param=POSTGRESQL_USER=theuser --param=POSTGRESQL_PASSWORD='Thepassword1!' --env=POSTGRESQL_MAX_PREPARED_TRANSACTIONS=100 --template=postgresql-persistent


oc new-app --param=MQ_USERNAME=theuser --param=MQ_PASSWORD='Thepassword1!' --template=amq63-persistent

oc create -f persistent-volume-claim.yml

mvn fabric8:deploy -P openshift

oc scale statefulset spring-boot-camel-jta-xa --replicas 3

NOTE: for OCP 4 the StateFullSet has apiVersion: apps/v1 and not apiVersion: apps/v1beta1

=== PostgreSQL nested XA

Tried to get nested transaction working, as shown in the camel routes.
But I could not get it working with PostgreSQL.

reference: https://jdbc.postgresql.org/documentation/faq.html#xa-support

So transaction support is available, but not (yet) nested.

reference: https://www.postgresql.org/docs/10/sql-begin.html

=== Spring Boot Recovery Controller

We have now transaction enabled in our application.
And scaling via the StatefulSet configuration is also enable.
But what if you scale up to 3 pods and need to scale down to one pod because the load of the app is not high enough.
If there are still pending transactions then the
https://github.com/snowdrop/narayana-spring-boot/tree/master/openshift/recovery-controller[Recovery Controller] will keep the needed Pod alive until the transactions are finished.

The Recovery Controller guarantees that when the application is scaled down, all instances, that are terminated, complete all their work correctly without leaving pending transactions.

The Spring Boot Narayana recovery controller allows to gracefully handle the scaling down phase of a StatefulSet by cleaning pending transactions before termination.
If a scaling down operation is executed and the pod is not clean after termination, the previous number of replicas is restored, hence effectively canceling the scaling down operation.

reference: https://access.redhat.com/documentation/en-us/red_hat_fuse/7.5/html-single/fuse_on_openshift_guide/index#spring-boot-narayana-recovery-controller

=== Recovery crash test

Still in need of a good reproducible scenario.

https://github.com/jboss-developer/jboss-eap-quickstarts/tree/7.0.0.Final/jta-crash-rec

- scenario: during scale down of the StatefulSet, pending transactions must be finished, before the Pod is terminated.
