spec:
  template:
    spec:
      containers:
        - resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 256Mi
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"server":{"undertow":{"io-threads":1, "worker-threads":2 }}}'
